### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/ruby-capstone-project#3]
Leave a comment please

**Comment by Kyle-Law** [comment]
Great job building such a heavy project! The fragmentation of functions has clearly demonstrated your competency on Ruby OOP. Since you're using 3rd party gem, I guess it's best practice to include a file named `Gemfile`, so that the user can simply install the gem with `bundle install` to the project root directory rather than installing to his entire local machine.

That's it from me. I reckon you gonna pass the project in no time 👍 👍

**Comment by dili021** [comment]
I don't know why you are surprised by passing code review (without rspec) on the first round, you have done an outstanding job! Really cool to see this.

**Comment by patriciachrysy** [comment]
Thank you guys
